baseURL = "https://www.nushackers.org/"
languageCode = "en-us"
title = "NUS Hackers"
copyright = "NUS Hackers"
buildFuture = true
disqusShortname = "nushackers"
enableEmoji = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "emacs"
ignoreFiles = ["\\.scss$"]
googleAnalytics = "UA-141681743-1"
rssLimit = 10

[params]
  description = "NUS Hackers"

[permalinks]
  post = "/:year/:month/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "About"
  identifier = "About"
  weight = 1
  url = "/about"
[[menu.main]]
  name = "Community"
  identifier = "Community"
  weight = 2
  url = "/community"
[[menu.main]]
  name = "Events"
  identifier = "Events"
  weight = 3
  url = "/about/#what-we-do"
[[menu.main]]
  name = "Contact"
  identifier = "Contact"
  weight = 4
  url = "/contact"
