baseURL = "https://www.nushackers.org/"
languageCode = "en-us"
title = "NUS Hackers"
copyright = "NUS Hackers"
buildFuture = true
disqusShortname = "nushackers"
enableEmoji = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "emacs"
ignoreFiles = ["\\.scss$"]
rssLimit = 10

[params]
  description = "NUS Hackers"
  academicYear = "2425"
  semester = 2

[permalinks]
  post = "/:year/:month/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "About"
  identifier = "About"
  weight = 1
  url = "/about"
[[menu.main]]
  name = "Community"
  identifier = "Community"
  weight = 2
  url = "/community"
[[menu.main]]
  name = "Archive"
  identifier = "Archive"
  weight = 3
  url = "/archive"
[[menu.main]]
  name = "Contact"
  identifier = "Contact"
  weight = 4
  url = "/contact"
[[menu.main]]
  name = "RSS"
  identifier = "RSS"
  weight = 5
  url = "/index.xml"
[[menu.main]]
  name = "Join Us"
  identifier = "Join Us"
  weight = 6
  url = "/join-coreteam"
